version: "2"
checks:
  file-lines:
    enabled: false
  method-count:
    config:
      threshold: 75
  method-lines:
    config:
      threshold: 250
plugins:
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
      - php:
  phpmd:
    enabled: true
    config:
      rulesets: "mdConfig.xml"
  sonar-php:
    enabled: true
    checks:
      php:S1192:
        enabled: false
      php:S138:
        enabled: false
      php:S1448:
        enabled: false
      php:S3776:
        enabled: false
      php:S1172:
        enabled: false
exclude_patterns:
  - "i18n/"
  - "db_patches/"
  - "tests/parserTests"
